dubbo:
  registries:
    demoZK:
      protocol: zookeeper
      timeout: 3s
      address: 127.0.0.1:2181
  consumer:
    references:
      IGreeter:
        protocol: dubbo
        interface: com.ganodermaking.learningapi.api.IGreeter